### ISSUE TITLE
Question about optimization options of clang

### ISSUE THREAD

**Issue by lxw-1006** [BinTuner/Dev#7]
Could I asked  a question. GCC is used as the optimization option in the original code. The paper also conducted experiments on llvm optimization options. What specific optimization options are used?

**Comment by BinTuner** [comment]
Thank you very much for your interest in our paper and for being prepared to try out BinTuner!

BinTuner is an auto-tuning framework, which can deliver a near-optimal binary code that reveals much more differences than -Ox settings.

That means you can feel free to add any option to extend or modify the array FLAGS = ['reorder-blocks', 'reorder-functions',  'inline-functions', 'unswitch-loops'] in the main.py program depending on the compiler version. Please note that different compiler versions may support different options, make sure that the choices you add are a match for the compiler you configured (for iterative compilation), otherwise you will get compilation errors.

For clang, please refer to the configuration methods under main_clang.py, for example, LLVM_FLAGS_fno = ['blocks', 'borland-extensions', 'delayed-template-parsing', 'fast-math',], LLVM_FLAGS_mno = ['backchain', 'incremental-linker-compatible', 'global-merge'], LLVM_FLAGS_On = ['gnu-runtime', 'stack-protector-all'], LLVM_FLAGS_Off = ['sanitize-blacklist', 'crash-diagnostics'], there are very detailed configuration methods and use cases here. https://github.com/BinTuner/Dev/blob/main/BinTuner/examples/gccflags/main_clang.py To double check before running to make sure the paths to all program (you will compile) files needed to compile are configured, otherwise you will get compilation errors and failures.

In addition, we use Z3 Prover to analyze all generated optimization option sequences for conflicts and make changes to conflicting options for greater compiling success. For more details, please refer [Z3Prover](https://github.com/BinTuner/Dev/blob/main/BinTuner/opentuner/search/Z3Prover.py).

Thanks again for your interest and feedback!

**Comment by lxw-1006** [comment]
> Thank you very much for your interest in our paper and for being prepared to try out BinTuner!
> 
> BinTuner is an auto-tuning framework, which can deliver a near-optimal binary code that reveals much more differences than -Ox settings.
> 
> That means you can feel free to add any option to extend or modify the array FLAGS = ['reorder-blocks', 'reorder-functions', 'inline-functions', 'unswitch-loops'] in the main.py program depending on the compiler version. Please note that different compiler versions may support different options, make sure that the choices you add are a match for the compiler you configured (for iterative compilation), otherwise you will get compilation errors.
> 
> For clang, please refer to the configuration methods under main_clang.py, for example, LLVM_FLAGS_fno = ['blocks', 'borland-extensions', 'delayed-template-parsing', 'fast-math',], LLVM_FLAGS_mno = ['backchain', 'incremental-linker-compatible', 'global-merge'], LLVM_FLAGS_On = ['gnu-runtime', 'stack-protector-all'], LLVM_FLAGS_Off = ['sanitize-blacklist', 'crash-diagnostics'], there are very detailed configuration methods and use cases here. https://github.com/BinTuner/Dev/blob/main/BinTuner/examples/gccflags/main_clang.py To double check before running to make sure the paths to all program (you will compile) files needed to compile are configured, otherwise you will get compilation errors and failures.
> 
> In addition, we use Z3 Prover to analyze all generated optimization option sequences for conflicts and make changes to conflicting options for greater compiling success. For more details, please refer [Z3Prover](https://github.com/BinTuner/Dev/blob/main/BinTuner/opentuner/search/Z3Prover.py).
> 
> Thanks again for your interest and feedback!

Thanks very much for your answer！
